import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQueryClientProvider } from "@/components/ReactQueryClientProvider";
import { Toaster } from "@/components/ui/toaster";
import { AppContextProvider } from "@/context/AppContext";
import { SearchContextProvider } from "@/context/SearchContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body className={inter.className}>
          <AppContextProvider>
            <SearchContextProvider>{children}</SearchContextProvider>
          </AppContextProvider>
          <Toaster />
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
